### PR TITLE
Update packages/site/src/pages/_app.tsx

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
fix issue #447

Hi [DavieReid](https://github.com/DavieReid),

Just trying to jump on this issue, please check it out

### CODE REVIEW

**Comment by DavieReid** [comment]
Hi, thanks for picking this up so quickly!

However, this is just applying the workaround mentioned in the issue, and we don't use the open api component on the mosaic site at the moment anyway.

I would prefer that we took a look at the build of the open api component so that it's css file includes the swagger css.  You can see it's included here --> https://github.com/jpmorganchase/mosaic/blob/main/packages/open-api-component/src/styles.ts

If you build the component and then look in the `dist` folder at the styles.css file you will only see the CSS from here --> https://github.com/jpmorganchase/mosaic/blob/main/packages/open-api-component/src/OpenAPI/styles.css.ts

Ideally, the following CSS import would correctly style the swagger component:

```
import '@jpmorganchase/mosaic-open-api-component/index.css';
```

**Comment by viktoriussuwandi** [comment]
Thanks for your suggestion @DavieReid, already update import statement as mentioned

**Comment by DavieReid** [comment]
> Thanks for your suggestion @DavieReid, already update import statement as mentioned

This is not what I suggested.  Your fix does not address the root cause of the problem.

**Comment by DavieReid** [comment]
Closing as doesn't address the problem.

**Pull request closed without merging**
